#!/bin/sh

trap 'kill 0' INT TERM PIPE

shopt -s lastpipe
set -o pipefail

alias info='echo -e "\x1b[1;32minfo\x1b[0m"'
alias warn='echo -e ".print \x1b[1;33mwarn\x1b[0m"'
alias err='echo -e ".print \x1b[1;31merror\x1b[0m"'
alias fatal='echo -e "\x1b[1;37;41mfatal\x1b[0m"'
alias probetags='ffprobe -v quiet -output_format json -show_entries format_tags'

dirname "$0" | read homedir

declare -a pids

read -d '' tagjq<<-'EOF'
.format.tags // {}
| del(
	.major_brand,
	.minor_version,
	.compatible_brands,
	.encoder
)
EOF

function diffnames() {
	local -a result=()
	local name exists

	for name in "$@"; do
		for exists in "${tagnames[@]}"; do
			test "$name" == "$exists" && continue 2
		done

		result+=("$name")
	done

	test "${#result[@]}" -eq 0 && return

	printf "%s\n" "${result[@]}"
}

function createnames() {
	local name

	for name in "$@"; do
		# we won't have to ignore a value more than once per thread,
		# but there's no other way to win the race when we don't
		# have semaphores
		echo "insert or ignore into tagnames(tagname) values('$name');"
	done
}

function inserttags() {
	local inode="$1"
	local name value
	shift

	jq -r 'to_entries[] | "\(.key) \(.value)"' <<<"$@" \
	| while read name value; do
		cat - <<-EOF
		insert  into tagvalues(tagvalue, inode, tagnameid)
		select  '${value//\'/\'\'}'
		       ,$inode
		       ,tn.id
		  from  tagnames tn
		 where  tn.tagname = '$name'
		;
		EOF
	done
}

function createpaths() {
	local root="$1"
	local pathparts part

	echo "${2#$root/}" | IFS=/ read -a pathparts

	for part in "${pathparts[@]}"; do
		cat - <<-EOF
		insert or ignore into paths(name, parentid)
		select  '$part'
		       ,id
		  from  fullpaths
		 where  fullpath = '$root'
		;
		EOF

		root="$root/$part"
	done
}

function createfile() {
	local file="$1"
	local inode="$2"

	cat - <<-EOF
	insert into files(id, inode)
	select  fp.id
	       ,$inode
	  from  fullpaths fp
	 where  fp.fullpath = '$file'
	returning 'created file', '$inode', '$file'
	;
	EOF
}

function closewrite() {
	local root="$1"
	local inode="$2"
	local file="$3"
	local tags tempnames newnames

	read lastinode

	if test "$inode" -ne "${lastinode:-0}"; then
		echo "insert into inodes(inode) values($inode);"

		if ! probetags "$file" | jq -c "$tagjq" | read tags; then
			warn "failed to read tags from '$file'"
			return 1
		elif test "$tags" == '{}'; then
			warn  "no tags found in file '$file'"
		elif ! echo "$tags" | jq -r 'keys[]' | readarray -t tempnames; then
			fatal "failed to extract tag names from '$tags' for '$file'" >&2
		elif ! diffnames "${tempnames[@]}" | readarray -t newnames; then
			warn "couldn't difference tag names" # this won't happen
		elif ! createnames "${newnames[@]}"; then
			err "couldn't create statements for new tagnames '${newnames[@]}'"
		elif ! inserttags "$inode" "$tags"; then
			fatal "couldn't create statements for new tagvalues" >&2
		else
			echo ".print `info "added ${#tempnames[@]} tags for '$inode'"`"
		fi

		tagnames+=("${newnames[@]}")
	fi

	createpaths "$root" "$file"

	createfile "$file" "$inode"
}

function initdb() {
	local root="$1"
	local lastinode=0
	local inode file

	find "$root" -type f -printf "%i %p\n" \
	| sort -k 1g \
	| while read inode file; do
		closewrite "$root" "$inode" "$file" <<<"$lastinode"

		lastinode="$inode"
	done

	echo ".print `info "finished processing tree '$root'"`"
}

function createdb() {
	local dir="$1"
	local db="$2"

	test -e "$db" && {
		info "removing existing database file \c"
		rm -v "$db"
	} >&2

	cat "$homedir/createdb.sql"

	echo "insert into paths(name) values('$dir');"

	initdb "$dir"
}

function remove() {
	local file="$1"
	local inode="$2"
	local linkcount

	read linkcount

	cat - <<-EOF
	delete  from files
	 where  id = (
	  select  fp.id
	    from  fullpaths fp
	   where  fp.fullpath = '$file')
	;
	delete  from paths
	 where  id = (
	  select  fp.id
	    from  fullpaths fp
	   where  fp.fullpath = '$file')
	;
	.print removed references to '$file'
	EOF

	test "$linkcount" -lt 2 && cat - <<-EOF
	delete  from tagvalues
	 where  inode = '$inode'
	;
	delete  from inodes
	 where  inode = '$inode'
	;
	.print removed inode $inode and values for '$file'
	EOF
}

function moveddirto() {
	dir="$1"
	oldid="$2"

	if test -n "$oldid"; then
		# for simple renaming we could just update the name in paths,
		# but when the directory has moved around in the tree it gets
		# more complicated; unconditional create and update is sorta
		# ham-fisted, and it leaves an orphan, but the cleanup proc
		# will fix it
		cat - <<-EOF
		update  paths
		   set  parentid = (
		  select  fp.id
		    from  fullpaths fp
		   where  fp.fullpath = '$dir')
		 where  parentid = $oldid
		;
		EOF
	else
		# an amalgam of initdb and movefileto that indexes new files,
		# but checks each inode one at a time, instead of relying on
		# the sorted order of the list for finding duplicate inodes
		#  when moving on the same filesystem; when copying or moving
		# from a different filesystem, this is a no-op, but close_write
		# will pick up new files one at a time
		find "$dir" -type f -printf "%i %p\n" \
		| while read inode file; do
			echo "select inode from inodes where inode = $inode" \
			| sqlite3 -readonly "$db" \
			| closewrite "$dir" "$inode" "$file"
		done
	fi
}

function movedfileto() {
	dir="$1"
	file="$2"
	inode="$3"
	oldid="$4"

	if test -n "$oldid"; then
		cat - <<-EOF
		update  files
		   set  id = (
		  select  fp.id
		    from  fullpaths fp
		   where  fp.fullpath = '$file')
		 where  id = $oldid
		;
		EOF
	else
		echo "select inode from inodes where inode = $inode" \
		| sqlite3 -readonly "$db" \
		| closewrite "$dir" "$inode" "$file"
	fi
}

function movedto() {
	local dir="$1"
	local file="$2"
	local inode="$3"
	local filetype="$4"
	local oldid

	read oldid

	test -n "$oldid" && createpaths "$dir" "$file"

	if test "$filetype" == "d"; then
		moveddirto "$file" "$oldid"
	else
		movedfileto "$dir" "$file" "$inode" "$oldid"
	fi

	cat - <<-EOF
	delete  from transients
	 where  cookie = '$cookie'
	;
	.print `info "finished move_to event for '$file'"`
	EOF
}

function cleandb() {
	db="$1"
	local now file inode linkcount

	echo ".print `info "starting cleanup"`"

	date +"%s" | read now

	cat - <<-EOF|
	select  file
	       ,inode
	       ,linkcount
	  from  pruned
	 where  $now - unixepoch(created) > 5
	EOF
	sqlite3 -readonly "$db" \
	| while IFS='|' read file inode linkcount; do
		remove "$file" "$inode" <<<"$linkcount"
	done

	cat - <<-EOF
	delete  from transients
	 where  $now - unixepoch(created) > 5
	returning 'removed aged transient', *
	;
	delete  from paths
	 where  exists (
	   select  1
	     from  orphans o
	    where  o.id = paths.id)
	returning 'removed path', *
	;
	.print `info "swept old records and orphans"`
	EOF
}

function syncdb() {
	local root="$1"
	local db="$2"
	local inode file lastinode=0 currlinks=0

	find "$root" -type f -printf "%i %p\n" \
	| while read inode file; do
		echo "insert into sync(inode, pathname) values($inode, '$file');";
	done | sqlite3 -bail "$db" || return 1

	echo "select inode, inodepath, linkcount from removed order by inode" \
	| sqlite3 -readonly "$db" \
	| while IFS='|' read inode file linkcount; do
		test "$inode" -ne "$lastinode" && currlinks="$linkcount" || let currlinks--
		remove "$file" "$inode" <<<"$currlinks"
		lastinode="$inode"
	done | sqlite3 -bail "$dbbase.db" || return 1

	lastinode=0
	echo "select inode, pathname, tagged from unsynced order by inode" \
	| sqlite3 -readonly "$db" \
	| while IFS='|' read inode file tagged; do
		test "$tagged" -gt 0 && lastinode="$inode"
		closewrite "$root" "$inode" "$file" <<<"$lastinode"
		lastinode="$inode"
	done | sqlite3 -bail "$dbbase.db" || return 1

	cleandb "$db" | sqlite3 -bail "$dbbase.db" || return 1

	cat - <<-EOF|
	delete from sync;
	vacuum;
	.print `info "finished sync '$db' on dir '$root'"`
	EOF
	sqlite3 -bail "$dbbase.db" || return 1
}

function listen() {
	local dir="$1"
	local db="$2"
	local events cookie file inode filetype

	echo "select tagname from tagnames" | sqlite3 -readonly "$db" | readarray -t tagnames

	inotifywait -m -r -e create -e close_write -e move -e delete --format "%e %c %w%f" "$dir" \
	| while read events cookie file; do
		[[ "$events" == *ISDIR* ]] && filetype=d || filetype=f
		
		if ! stat --printf "%i" "$file" 2>/dev/null; then
			# this happens on DELETE and MOVED_FROM; directories don't care
			# about inodes (or subsequent linkcounts)
			echo "select inode from inodepaths where inodepath = '$file'" \
			| sqlite3 -readonly "$db"
		fi | read inode

		events="CLEAN_DB,${events/,ISDIR}"

		while read event; do
			case "$event" in
				CREATE) test "$filetype" == f -a "`stat --printf "%h" "$file"`" != "1" &&
				echo "select inode from inodes where inode = $inode" \
				| sqlite3 -readonly "$db" \
				| closewrite "$dir" "$inode" "$file"
				;;

				DELETE) test "$filetype" == d ||
				echo "select count(1) from files where inode = $inode" \
				| sqlite3 -readonly "$db" \
				| remove "$file" "$inode"
				;;

				CLOSE_WRITE) closewrite "$dir" "$inode" "$file" <<<0 ;;

				MOVED_FROM) cat - <<-EOF
				insert into transients(cookie, oldpath)
				select  '$cookie'
				       ,id
				  from  fullpaths
				 where  fullpath = '$file'
				returning 'created transient', *
				;
				EOF
				;;

				MOVED_TO) cat - <<-EOF|
				select  oldpath
				  from  transients
				 where  cookie = '$cookie'
				EOF
				sqlite3 -readonly "$db" | movedto "$dir" "$file" "$inode" "$filetype"
				;;

				CLEAN_DB) cleandb "$db" ;;
			esac | sqlite3 -echo -bail "$db" >&2
		done <<<"${events//,/$'\n'}"
	done
} >&2

for arg in "$@"; do
	if test "$arg" == "-rebuild"; then
		test -n "$SYNC_CAT" && {
			echo "only one of -rebuild or -sync allowed for a directory"
			exit 1
		}
		BUILD_CAT=1
		continue
	elif test "$arg" == "-sync"; then
		test -n "$BUILD_CAT" && {
			echo "only one of -rebuild or -sync allowed for a directory"
			exit 1
		}
		SYNC_CAT=1
		continue
	fi

	readlink -f "$arg" | read dir

	test -d "$dir" || {
		fatal "'$dir' does not specify a directory"
		exit 1
	}

	dbbase="$homedir/${dir//\//_}"

	test -f "$dbbase.db" || BUILD_CAT=1

	case 1 in
	"$BUILD_CAT") createdb "$dir" "$dbbase.db" | sqlite3 -bail "$dbbase.db" || {
		fatal "failed to create database"
		exit 1
	}
	;;
	"$SYNC_CAT") syncdb "$dir" "$dbbase.db" || {
		fatal "failed to sync database"
		exit 1
	}
	;;
	esac

	if test -z "$NO_CAT_DAEMON"; then
		(listen "$dir" "$dbbase.db" 2>&1 | tee "$dbbase.log") &
		pids+=("$!")
	fi

	unset BUILD_CAT SYNC_CAT
done >&2

info "successfully started process $$ with '${#pids[@]}' pid(s): '${pids[@]}'" >&2

wait "${pids[@]}"

