#!/bin/sh

trap 'kill 0' INT TERM PIPE

shopt -s lastpipe
set -o pipefail

alias info='echo -e "\x1b[1;32minfo\x1b[0m"'
alias warn='echo -e ".print \x1b[1;33mwarn\x1b[0m"'
alias err='echo -e ".print \x1b[1;31merror\x1b[0m"'
alias fatal='echo -e "\x1b[1;37;41mfatal\x1b[0m"'
alias probetags='ffprobe -v quiet -output_format json -show_entries format_tags'

read -d '' tagjq<<-'EOF'
.format.tags // {}
| del(
	.major_brand,
	.minor_version,
	.compatible_brands,
	.encoder
)
EOF

declare -a tagnames=()
declare -a pids=()

function createdb() {
	local db="${1//\//_}.db"

	test -e "$db" && {
		info "removing existing database file \c"
		rm -v "$db"
	} >&2

	echo "insert into paths(name) values('$1');" \
	| sqlite3 -bail -init ./createdb.sql "$db" >&2 || return 1

	info "created database '$db'" >&2

	echo "$db"
}

function diffnames() {
	local -a result=()

	for name in "$@"; do
		for exists in "${tagnames[@]}"; do
			test "$name" == "$exists" && continue 2
		done

		result+=("$name")
	done

	test "${#result[@]}" -eq 0 && return

	printf "%s\n" "${result[@]}"
}

function createnames() {
	for name in "$@"; do
		# we won't have to ignore a value more than once per thread,
		# but there's no other way to win the race when we don't
		# have semaphores
		echo "insert or ignore into tagnames(tagname) values('$name');"
	done
}

function inserttags() {
	local inode="$1"
	shift

	jq -r 'to_entries[] | "\(.key) \(.value)"' <<<"$@" \
	| while read name value; do
		# there's a rare case when we move a tree from outside the root and
		# it contains inodes that are already under the root using other names,
		# but we bave no good way to know that (w/o constantly hitting the db) so
		# we ignore the unique key violation (the value will be the same, anyway)
		cat - <<-EOF
		insert  or ignore into tagvalues(tagvalue, inode, tagnameid)
		select  '${value//\'/\'\'}'
					 ,$inode
					 ,tn.id
			from  tagnames tn
		 where  tn.tagname = '$name'
		;
		EOF
	done
}

function createpaths() {
	local root="$1"
	echo "${2#$root/}" | IFS=/ read -a pathparts

	for part in "${pathparts[@]}"; do
		cat - <<-EOF
		insert or ignore into paths(name, parentid)
		select  '$part'
		       ,id
		  from  fullpaths
		 where  fullpath = '$root'
		returning 'created path', '$root/$part'
		;
		EOF

		root="$root/$part"
	done
}

function createfile() {
	local file="$1"
	local inode="$2"

	cat - <<-EOF
	insert into files(id, inode)
	select  fp.id
	       ,$inode
	  from  fullpaths fp
	 where  fp.fullpath = '$file'
	returning 'created file', '$inode', '$file'
	;
	EOF
}

function create() {
	local dir="$1"
	local file="$2"
	local inode="$3"

	createpaths "$dir" "$file"

	createfile "$file" "$inode"
}

function closewrite() {
	local root="$1"
	local inode="$2"
	local lastinode="$3"
	local file="$4"

	if test "$inode" -ne "$lastinode"; then
		echo "insert into inodes(inode) values($inode);"

		if ! probetags "$file" | jq -c "$tagjq" | read tags; then
			warn "failed to read tags from '$file'"
			return 1
		elif test "$tags" == '{}'; then
			warn  "no tags found in file '$file'"
		elif ! echo "$tags" | jq -r 'keys[]' | readarray -t tempnames; then
			fatal "failed to extract tag names from '$tags' for '$file'" >&2
		elif ! diffnames "${tempnames[@]}" | readarray -t newnames; then
			warn "couldn't difference tag names" # this won't happen
		elif ! createnames "${newnames[@]}"; then
			err "couldn't create statements for new tagnames '${newnames[@]}'"
		elif ! inserttags "$inode" "$tags"; then
			fatal "couldn't create statements for new tagvalues" >&2
		else
			echo ".print `info "added ${#tempnames[@]} tags for '$inode'"`"
		fi

		tagnames+=("${newnames[@]}")
	fi

	create "$root" "$file" "$inode"
}

function initdb() {
	local root="$1"
	local lastinode=0

	find "$root" -type f -printf "%i %p\n" \
	| sort -k 1g \
	| while read inode file; do
		closewrite "$root" "$inode" "$lastinode" "$file"

		lastinode="$inode"
	done

	echo ".print `info "initialized database"`"
}

function remove() {
	local file="$1"
	local inode="$2"
	local linkcount="$3"

	cat - <<-EOF
	delete  from files
	 where  id = (
	  select  fp.id
	    from  fullpaths fp
	   where  fp.fullpath = '$file')
	;
	delete  from paths
	 where  id = (
	  select  fp.id
	    from  fullpaths fp
	   where  fp.fullpath = '$file')
	;
	.print removed references to '$file'
	EOF

	test "$linkcount" -lt 2 && cat - <<-EOF
	delete  from tagvalues
	 where  inode = '$inode'
	;
	delete  from inodes
	 where  inode = '$inode'
	;
	.print removed inode $inode and values for '$file'
	EOF
}

function moveddirto() {
	file="$1"
	oldid="$2"

	if test -n "$oldid"; then
		warn "filetype is dir and oldid is '$oldid'"
		# for simple renaming we could just update the name, but when
		# the directory has moved around in the tree it gets more
		# complicated; unconditional create and update is sorta ham-
		# fisted, and it leaves an orphan, but the cleanup proc will
		# fix it
		cat - <<-EOF
		update  paths
		   set  parentid = (
		  select  fp.id
		    from  fullpaths fp
		   where  fp.fullpath = '$file')
		 where  parentid = $oldid
		;
		EOF
	else
		warn "directory was moved into this tree from elsewhere"
		# if dir was moved/copied from somewhere else on the same filesystem, 
		# then this does effectively nothing, but the file close_write events
		# will do the job one at a time
		initdb "$file"
	fi
}

function movedfileto() {
	dir="$1"
	file="$2"
	inode="$3"
	oldid="$4"

	if test -n "$oldid"; then
		warn "filetype is NOT dir and oldid is '$oldid'"
		cat - <<-EOF
		update  files
		   set  id = (
		  select  fp.id
		    from  fullpaths fp
		   where  fp.fullpath = '$file')
		 where  id = $oldid
		;
		EOF
	else
		warn "file was moved into this tree from elsewhere"
		# FIXME: this calls createpaths unnecessarily
		closewrite "$dir" "$inode" 0 "$file"
	fi
}

function movedto() {
	dir="$1"
	file="$2"
	inode="$3"

	cat - | IFS='|' read oldid filetype

	createpaths "$dir" "$file"

	if test "$filetype" == "d"; then
		moveddirto "$file" "$oldid"
	else
		movedfileto "$dir" "$file" "$inode" "$oldid"
	fi

	cat - <<-EOF
	delete  from transients
	 where  cookie = '$cookie'
	;
	.print `info "finished move_to event for '$file'"`
	EOF
}

function cleandb() {
	db="$1"

	date +"%s" | read now

	cat - <<-EOF|
	select  file
	       ,inode
	       ,linkcount
	  from  pruned
	 where  $now - unixepoch(created) > 5
	EOF
	sqlite3 -bail "$db" \
	| while IFS='|' read file inode linkcount; do
		remove "$file" "$inode" "$linkcount"
	done

	cat - <<-EOF
	delete  from transients
	 where  $now - unixepoch(created) > 5
	;
	delete  from paths
	 where  exists (
	   select  1
	     from  orphans o
	    where  o.id = paths.id)
	returning 'removed path', *
	;
	.print `info "swept old records and orphans"`
	EOF
}

function listen() {
	local dir="$1"
	local db="$2"
	local inode linkcount filetype events cookie file

	#sqlite3 "$db" <<<"select tagname from tagnames" | readarray -t tagnames

	inotifywait -m -r -e create -e close_write -e move -e delete --format "%e %c %w%f" "$dir" \
	| while read events cookie file; do
		[[ "$events" == *ISDIR* ]] && filetype=d || filetype=f
		
		if test -e "$file"; then
			find "$file" -maxdepth 0 -printf "%i %n" | read inode linkcount
		else
			cat - <<-EOF|
			select  f.inode
			       ,count(links.id)
			  from  files       f
			  join  fullpaths   fp
			    on  f.id        = fp.id
			  join  files       links
			    on  f.inode = links.inode
			 where  fp.fullpath = '$file'
			 group
			    by  f.inode
			EOF
			sqlite3 "$db" | IFS='|' read inode linkcount
		fi

		events="${events/,ISDIR},CLEAN_DB"

		while read event; do
			case "$event" in
				# FIXME: the linkcount test is intended to ignore net-new files b/c they won't
				# have tags until close_write, with the unintended side-effect that fules linked
				# from outside the root won't have their tags indexed
				CREATE) test "$linkcount" -gt 1 -a "$filetype" == f && create "$dir" "$file" "$inode" ;;

				DELETE) test "$filetype" == d || remove "$file" "$inode" "$linkcount" ;;

				CLOSE_WRITE) closewrite "$dir" "$inode" "0" "$file" ;;

				MOVED_FROM) cat - <<-EOF
				insert into transients(cookie, oldpath, filetype)
				select  '$cookie'
				       ,id
				       ,'$filetype'
				  from  fullpaths
				 where  fullpath = '$file'
				returning 'created transient', *
				;
				EOF
				;;

				MOVED_TO) cat - <<-EOF|
				select  oldpath
				       ,filetype
				  from  transients
				 where  cookie = '$cookie'
				EOF
				sqlite3 "$db" | movedto "$dir" "$file" "$inode"
				;;

				CLEAN_DB) cleandb "$db" ;;
			esac | sqlite3 -bail "$db" >&2
		done <<<"${events//,/$'\n'}"

	done
}

for dir in "$@"; do
	readlink -f "$dir" | read dir

	test -d "$dir" || {
		fatal "'$dir' does not specify a directory"
		exit 1
	}

	if ! createdb "$dir" | read db; then
		fatal "failed to create database"
		exit 1
	elif ! initdb "$dir" | sqlite3 -bail "$db"; then
		fatal "failed to initialize database"
		exit 1
	fi

	listen "$dir" "$db" &
	pids+=($!)
done

info "successfully started process $$"

wait "${pids[@]}"

